import math
from datetime import datetime

from db_init import DB_TIMEZONE, get_db_connection

#TODO: check if I really need to save mal_id in the db, maybe I can just save the answer 
# and the question and the model and the prompt and the instructions and the tokens
# and the response time and the cost and the timestamp
#TODO: check if conversation_id needs to be received from chatgpt or if it can be generated by the db, 
# maybe I can just use the id of the conversation table as the conversation_id
def save_conversation(conversation_id, record, question, timestamp=None):
    timestamp = datetime.now(DB_TIMEZONE)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO conversations (
                    conversation_id, question, answer, model, instructions, prompt,
                    prompt_tokens, completion_tokens, total_tokens,
                    response_time, cost, timestamp
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
                RETURNING conversation_id
                """,
                (
                    conversation_id,
                    question,
                    record.answer,
                    record.model,
                    record.instructions,
                    record.prompt,
                    record.prompt_tokens,
                    record.completion_tokens,
                    record.total_tokens,
                    record.response_time,
                    record.cost,
                    timestamp,
                ),
            )
            conversation_id = cur.fetchone()[0]
        conn.commit()
    finally:
        conn.close()
    return conversation_id

#save judge feedback function
def save_judge_feedback(conversation_id, relevance, explanation):
    timestamp = datetime.now(DB_TIMEZONE)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO feedback (
                    conversation_id, source, relevance, explanation, timestamp
                ) VALUES (
                    %s, %s, %s, %s, %s
                )
                ON CONFLICT (conversation_id, source) DO UPDATE
                SET relevance = EXCLUDED.relevance,
                    explanation = EXCLUDED.explanation,
                    timestamp = EXCLUDED.timestamp
                """,
                (conversation_id, "judge", relevance, explanation, timestamp),
            )
        conn.commit()
    finally:
        conn.close()

#save feedback function
def save_user_feedback(conversation_id, score, explanation):
    timestamp = datetime.now(DB_TIMEZONE)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO feedback (
                    conversation_id, source, score, explanation, timestamp
                ) VALUES (
                    %s, %s, %s, %s, %s
                )
                ON CONFLICT (conversation_id, source) DO UPDATE
                SET score = EXCLUDED.score,
                    explanation = EXCLUDED.explanation,
                    timestamp = EXCLUDED.timestamp
                """,
                (conversation_id, "user", score, explanation, timestamp),
            )
        conn.commit()
    finally:
        conn.close()
